[package]
name = "empholite"
version = "0.2.0"
authors = ["Thomas Gideon <cmdln@thecommandline.net>"]

[dependencies]
actix-web = "0.7"
dotenv = "0.10"
env_logger = "0.5"
failure = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
