[package]
name = "shared"
version = "0.0.1"
authors = ["Thomas Gideon <cmdln@thecommandline.net>"]
edition = "2018"

[dependencies]
serde = { version = "^1.0.111", features = [ "derive" ] }
serde_json = "^1.0.53"
